Characters:
  - Алиса
  - Король Артур
  - Синдбад
  - Медуза
  - Красная Шапочка
  - Беовульф
  - Дракула
  - Шерлок Холмс
  - Человек-невидимка
  - доктор Джекилл
  - Робин Гуд
  - Снежный человек
  - Уолтер и Джесси
  - Флэш
Maps: 7
Players: 2